n = input()
n = n.replace('one', '1')
n = n.replace('two', '2')
n = n.replace('three', '3')
n = n.replace('four', '4')
n = n.replace('five', '5')
n = n.replace('six', '6')
n = n.replace('seven', '7')
n = n.replace('eight', '8')
n = n.replace('nine', '9')
print(n)
