-- 코드를 입력하세요
SELECT USER_ID	,NICKNAME,SUM(PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD ugb
INNER JOIN USED_GOODS_USER ugu
ON ugb.WRITER_ID = ugu.USER_ID
WHERE ugb.STATUS = 'DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES 